version: '3'
services:
  app:
    build: .
    command: pm2-dev ./app/server.js
    environment:
      NODE_ENV: development
    depends_on:
      - mongodb
    ports:
      - '5000:5000'
    volumes:
      - .:/home/nodejs/app
      - /home/nodejs/app/node_modules
  mongodb:
    image: mongo:4
    command: mongod
    ports:
      - '27017:27017'
